# Generated by Django 5.1.4 on 2024-12-24 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=255)),
                ('chiqarilgan_sana', models.DateField()),
                ('yaroqlilik_muddati', models.DateField()),
                ('mavjud_miqdori', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familya', models.CharField(max_length=255)),
                ('telefon_raqam', models.CharField(max_length=20)),
                ('manzil', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Mijozlar',
            },
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jami_narx', models.PositiveSmallIntegerField()),
                ('sana', models.DateField()),
                ('status', models.CharField(choices=[('Qabul qilingan', 'Qabul qilingan'), ('Yuborilgan', 'Yuborilgan'), ('Yetkazib berilgan', 'Yetkazib berilgan')], max_length=50)),
                ('mahsulot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mahsulot')),
                ('mijoz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mijoz')),
            ],
            options={
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
